#docker compose up  (will start all containers)
version: "3.8"

services:
  web: #docker compose run --service-ports web bash (to reach inside of compose)
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0 #each time docker compose up, it will run this command
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes: # add named variables to the volumes, it can only be deleted manually
  postgres_db:
